services:
  - type: web
    name: next-otf-widget
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: CACHE_SECONDS
        value: 60
